### ISSUE TITLE
Add »Toast this post«-button

### ISSUE THREAD

**Issue by janraasch** [janraasch/hugo-bearblog#1]
# »Toast this post«-button Context

On https://bearblog.dev posts & pages may be liked via a »Toast this post«-button:

<img width="252" alt="Screenshot 2020-09-04 at 09 07 28" src="https://user-images.githubusercontent.com/425211/92210117-6f66db80-ee8e-11ea-8730-9a3ab434be93.png">

See https://jan.bearblog.dev/toast/ for a live example.

# Goal

Ship this theme with a ready-to-go »Toast this post«-`<button>` 🍞 .

# Implementation Idea

We could implement a similar functionality via [netlify Functions](https://docs.netlify.com/functions/overview/). Then, using their git-connector, we can persist the `toasts`-count directly into the source `.md`-file.

**Comment by janraasch** [comment]
Even easier?!: Check out https://www.producthunt.com/posts/lyket.

**Comment by brandonprajogo** [comment]
I wonder if there is an alternative way to support these feature without using netlify and lyket? because I don't host my site on Netlify and don't want to pay for lyket. Thanks.

**Comment by janraasch** [comment]
Hi @brandonprajogo, 

we'd need some backend to store `toasts`. I suppose we could build a small `toast`-service (basically an open source `Lyket`-clone). 

Then you'd still need to run this `toast`-server yourself somewhere - which I also can't imagine to be free. E.g. running a small linux box is about 4 EUR a month at the moment.

I can't think of anything else... Is there some other solution you had in mind?

**Comment by janraasch** [comment]
Fixed with https://github.com/janraasch/hugo-bearblog/issues/100.
