### ISSUE TITLE
Blogs go to localhost:1313 on server

### ISSUE THREAD

**Issue by ThatOneCalculator** [janraasch/hugo-bearblog#18]
My website: https://blog.t1c.dev/

Upon going to https://blog.t1c.dev/blog/ and clicking on one of the blogs, it literally enters the address http://localhost:1313/rose-pine/ instead of https://blog.t1c.dev/online/ .

**Comment by janraasch** [comment]
Hi @ThatOneCalculator, thank you for reaching out ❤️.

My first guess would be that you have the `baseURL` set incorrectly.

Did you set `baseURL` (on your config.toml - see https://gohugo.io/getting-started/configuration/#all-configuration-settings) to `https://blog.t1c.dev/` when buildling the site?

Let me know, if that helps 👋🏻,
kind regards,
Jan

---

If that does not help, could you provide a link to the source repo of your blog, so I could have a quick look?

**Comment by ThatOneCalculator** [comment]
Hi! Sorry for the late response. Yes, it WAS set in my config.toml, which points to that not being the issue.

```
$ cat config.toml 

baseURL = "https://blog.t1c.dev/"

# The name of this wonderful theme ;-).
theme = 'hugo-bearblog'

# Basic metadata configuration for your blog.
title = "ThatOneCalculator's Blog ʕ•ᴥ•ʔ"
author = "ThatOneCalculator"
languageCode = "en-US"

# Generate a nice robots.txt for SEO
enableRobotsTXT = true

# Generate "Bearblog"-like URLs !only!, see https://bearblog.dev/.
disableKinds = ["taxonomy"]
ignoreErrors = ["error-disable-taxonomy"]
[permalinks]
  blog = "/:slug/"
  tags = "/blog/:slug"

[params]
  # The "description" of your website. This is used in the meta data of your generated html.
  description = "Hugo + Bear = :heart:"

  # The path to your "favicon". This should be a square (at least 32px x 32px) png-file.
  # Hint: It's good practise to also put a "favicon.ico"-file into your "static"-folder.
  favicon = "images/favicon.png"

  # These "images" are used for the structured data templates. This will show up, when  # services like Twitter or Slack want to generate a preview of a link to your site.
  # See https://gohugo.io/templates/internal#twitter-cards and
  # https://gohugo.io/templates/internal#open-graph.
  images = ["images/share.png"]

  # Another "title" :-). This one is used as the site_name on the Hugo's internal
  # opengraph structured data template.
  # See https://ogp.me/ and https://gohugo.io/templates/internal#open-graph.
  title = "ThatOneCalculator's Bear Blog ʕ•ᴥ•ʔ"

  # This theme will, by default, inject a made-with-line at the bottom of the page.
  # You can turn it off, but we would really appreciate if you don’t :-).
  # hideMadeWithLine = true
```

**Comment by ThatOneCalculator** [comment]
It also just seems to be a problem with Blog > Redirect, because going to the URL manually seems to be fine.

**Comment by janraasch** [comment]
Hi @ThatOneCalculator, seems strange 😅.

So the template which is being used to render that `list` of blog posts is

```html
    <li>
      <span>
        <i>
          <time datetime='{{ .Date.Format "2006-01-02" }}' pubdate>
            {{ .Date.Format "02 Jan, 2006" }}
          </time>
        </i>
      </span>
      <a href="{{ .Permalink }}">{{ .Title }}</a>
    </li>
```

see https://github.com/janraasch/hugo-bearblog/blob/master/layouts/_default/list.html#L19.

Looking at the HTML source

![Screenshot 2021-02-09 at 08 21 09](https://user-images.githubusercontent.com/425211/107329386-5ce17580-6ab0-11eb-9d8f-5c4b68ac3ba5.png)

**we can decude that the `Permalink` of a blog post is `http://localhost....`** *for some reason* 😇.

Here is some documentation on `Page.Permalink`: https://gohugo.io/variables/page/ and https://gohugo.io/content-management/urls/.

Maybe that already gives you a clue 😊.

Otherwise, could you share the contents of your `content/blog/directory`?

**Comment by ThatOneCalculator** [comment]
![image](https://user-images.githubusercontent.com/44733677/107402390-bea5dd80-6ab8-11eb-9867-13012872487e.png)
All that's in content/blog are these md files and the log.txt from my text editor.

**Comment by ThatOneCalculator** [comment]
I also took a look at the documentation, and despite what I tried, I couldn't get it to work...

**Comment by janraasch** [comment]
Could you please also share the contents of _index.md and the online.md.

Maybe I can spot something there 😅.

**Comment by ThatOneCalculator** [comment]
@janraasch any other ideas?

**Comment by janraasch** [comment]
Hi @ThatOneCalculator, I am sorry for the late response 😌. Could you gimme access to the full source code of your blog? I think at this point that's probably the easiest so I can try to reproduce and then hopefully pin down the problem.
