### ISSUE TITLE
Conflicting colors for code blocks on dark vs on light

### ISSUE THREAD

**Issue by ajorg** [janraasch/hugo-bearblog#19]
I'm using the `lovelace` style for syntax highlighting. It looks great on a light theme:

![image](https://user-images.githubusercontent.com/260569/111091415-15f00100-84f0-11eb-83fa-41800fbcec6c.png)

But on a dark theme the same looks unreadable:

![image](https://user-images.githubusercontent.com/260569/111091445-2bfdc180-84f0-11eb-835d-808901bc2aba.png)

From what I can tell, Chroma styles are supposed to control the background color as well as all the font colors, but the bearblog theme is interfering. I've tried to get the theme to get out of the way, by removing bits of CSS that look like they they're probably causing problems, but it doesn't quite fix the issue all the way, and I also don't love having a light theme code block on a dark theme page.

```diff
diff --git a/layouts/partials/style.html b/layouts/partials/style.html
index 6d1a66b..b1798bf 100644
--- a/layouts/partials/style.html
+++ b/layouts/partials/style.html
@@ -64,11 +64,10 @@

   code {
     padding: 2px 5px;
-    background-color: #f2f2f2;
   }

   pre code {
-    color: #222;
+    color: reset;
     display: block;
     padding: 20px;
     white-space: pre-wrap;
@@ -136,14 +135,6 @@
       color: #8cc2dd;
     }

-    code {
-      background-color: #777;
-    }
-
-    pre code {
-      color: #ddd;
-    }
-
     blockquote {
       color: #ccc;
     }
```

I've wondered if in some sense this is just Hugo and Chroma's fault for not supporting light and dark themes more robustly, but I'm also just wondering if there's a way to adjust the Bear theme to do the right thing.

I've also looked for better Chroma styles, but it seems impossible to find a style that's readable in both light and dark themes.

**Comment by janraasch** [comment]
Hi Andrew 👋,

have you tried to reaching out on the [Hugo Forum](https://discourse.gohugo.io/)?

I think that could be a good place to start.

 I myself am not using all that much `<code>` these days - not when blogging that is 🤓...

Maybe somebody else can chime in 🤞 😁.

Cheers,
Jan

**Comment by ajorg** [comment]
I have not, but fair enough - I will.
If I come up with a patch that fixes this, would you be likely to accept it?

**Comment by janraasch** [comment]
Hi @ajorg, if it's a problem with this theme, sure definitely 👌. Have a good weekend 🏝 👋.
