### ISSUE TITLE
Hide draft posts

### ISSUE THREAD

**Issue by aparcar** [janraasch/hugo-bearblog#3]
Posts with draft = 1 shouldn't be rendered in the blog post list.

**Comment by janraasch** [comment]
Hi @aparcar, 

I see you are making some progress on configuring https://aparcar.org 🚀 👍🏻 .

To your question: The [frontmatter configs in Hugo](https://gohugo.io/content-management/front-matter/) (`toml`, `yaml`, `json`) all understand `boolean` (`true` / `false`)-values, so simply use

```toml
draft = true
```

in case you're using the `toml`-format. That will mark your post as a `draft` and thus it will not show up anywhere on the rendered blog.

Again, I hope that helps.

Let me know if you have any other/follow-up questions.

Greetings to Hawaii as always 🌞 😄 ,
Jan

**Comment by aparcar** [comment]
Oh yes it works, I first though it would require a modification to the theme itself.

Greetings from Hawaii :surfer:
