### ISSUE TITLE
Darkmode CSS overwriting Syntax Highlighting

### ISSUE THREAD

**Issue by keyneston** [janraasch/hugo-bearblog#31]
I'm not a web developer, just a backend developer. So apologies for any stupidity or bad terminology here.

I was migrating my blog to bearblog and I'm having an issue with the syntax highlighting. Specifically I'm having issues with punctuate being rendered in black, instead of the color that chroma monokai is setting.

<img width="659" alt="CleanShot 2021-06-08 at 17 51 48@2x" src="https://user-images.githubusercontent.com/39023/121217897-9077b500-c882-11eb-878b-5f83c2600d82.png">

Looking at this in firefox it appears if I'm reading this correctly to be an issue of `pre code` from `@(prefers-color-cheme: dark)`.

<img width="295" alt="CleanShot 2021-06-08 at 17 51 34@2x" src="https://user-images.githubusercontent.com/39023/121218014-a8e7cf80-c882-11eb-8d4f-fc12a6793ecf.png">

## Version Info

Bearblog Commit: 6408d03c688d8998476f35ee3beca49fc7b990b1

```
$ ./scripts/hugo version
hugo v0.83.1 darwin/amd64 BuildDate=unknown
```

**Comment by BBaoVanC** [comment]
I'm seeing this issue too.

**Comment by meleu** [comment]
That's the only reason I didn't choose this awesome theme. Leaving a comment here just to be notified if/when this issue is solved. :innocent:

**Comment by janraasch** [comment]
Hi @BBaoVanC, @meleu & @keyneston, could one of you check, if https://github.com/janraasch/hugo-bearblog/pull/25 solves this issue? Thank you 🙏🏻.

**Comment by janraasch** [comment]
I'll close this.

If the issue still persists, let me know, and we'll reopen this puppy 🐶 😁.
