### ISSUE TITLE
HTML5 validation failures

### ISSUE THREAD

**Issue by dijitali** [janraasch/hugo-bearblog#33]
Just having a play with this theme (thanks for your work, it looks awesome!) and spotted a couple of minor things are currently being flagged by the [W3C HTML Validator](https://validator.w3.org/nu/):

![image](https://user-images.githubusercontent.com/4665045/122860091-fe0cf200-d314-11eb-9430-9115b274363d.png)

1. It's apparently invalid to use `http-equiv` for any HTTP header, only those [listed in the Pragma directives here](https://www.w3.org/TR/2014/WD-html5-20140617/document-metadata.html#pragma-directives)
2. Use of the `itemprop` attribute requires the `itemscope` and `itemtype` to be defined.

I'm happy to pop some PRs up for these but I also wondered if you'd like the idea/would accept a PR to add a Github Action to automatically validate the build of the example site with the checker going forward?

**Comment by janraasch** [comment]
Hi @dijitali, thank you for getting in touch 👋.

## http-equiv

This might not be »valid«, but it's just a fun meta-tag we inherited from the original bearblog. See

* Original: https://bearblog.dev/accounts/login/?next=/dashboard/ 
* Example blog: https://herman.bearblog.dev

The source code is here: https://github.com/HermanMartinus/bearblog/blob/master/templates/base.html#L5.

ℹ️ Here's the story behind this non-standardised HTTP header: https://xclacksoverhead.org/home/about

## itemprop

This one baffles me a little bit. We are using `Hugo`s very own `_internal/schema.html`-template here. The code is over at https://github.com/gohugoio/hugo/blob/master/tpl/tplimpl/embedded/templates/schema.html.

I went and checked what's up on the `Hugo News`-blog and they actually use it just in exactly the same way we do. Thus they get the same error on the w3c-validator, see https://validator.w3.org/nu/?doc=https%3A%2F%2Fgohugo.io%2Fnews%2F

If you want to persue this further I'd suggest opening up an issue on the main Hugo repo, which includes the `_internal/schema.html`-template, so this can be fixed centrally.

➡️ Thus - I think - we'll just have to live with these errors on the validator (for now?).

-----

If you have a requirement for your personal website to be 100% valid against the w3c-validator you may overwrite the

* `baseof.html` (This includes the non-valid header) and
* `seo_tags.html` (This includes the non-valid item props)

templates locally.

I hope that helps 🙏.

Kind regards and have a good weekend 🏝.

**Comment by dijitali** [comment]
Thanks for such a considered response!  Totally on board with you on both these points, I just hadn't realised how much was inherited by this repo.  

The first one would be ideal if it could be set as an actual HTTP response header but totally outside the scope of this and it looks like the second point has already been raised as a Hugo bug in https://github.com/gohugoio/hugo/issues/7431.

Hope you have a great weekend too!
