### ISSUE TITLE
CSS rule typo: word-wrap

### ISSUE THREAD

**Issue by ilmari-lauhakangas** [janraasch/hugo-bearblog#40]
The body element has the rules

```
word-wrap: break-word;
overflow-wrap: break-word;
```

https://github.com/janraasch/hugo-bearblog/blob/2fa45b92a24e76a610f86f1e039225be5d8cb695/layouts/partials/style.html#L9

However, there is no such rule as word-wrap. The correct rule name is [word-break](https://developer.mozilla.org/en-US/docs/Web/CSS/word-break).

I did not submit a PR because I am not sure what the intended goal is. MDN says the break-word value for word-break is deprecated and

> Has the same effect as word-break: normal and overflow-wrap: anywhere, regardless of the actual value of the overflow-wrap property.

**Comment by janraasch** [comment]
Hi @ilmari-lauhakangas, nice catch ⚾️ 👍.

> I did not submit a PR because I am not sure what the intended goal is.

I am not sure either 😅. This whole repo is a _blatant_ 😛 copy & paste from the original bearblog, see

https://github.com/HermanMartinus/bearblog/blob/2ee04f04efa172fd32b63d0480692f405106b943/templates/styles/main.css

You could check in with @HermanMartinus - the man behind this wonderful idea. I am sure he will appreciate your input.

**Comment by ilmari-lauhakangas** [comment]
Thanks, I copied the issue over to bearblog.

**Comment by janraasch** [comment]
Thanks, then we'll follow along over there https://github.com/HermanMartinus/bearblog/issues/115.

**Comment by ilmari-lauhakangas** [comment]
Ok now I see from the notes in https://caniuse.com/wordwrap that overflow-wrap used to be called word-wrap in ancient times and IE11 only supports word-wrap. I was thrown off by Firefox reporting it as an invalid name.
