### ISSUE TITLE
external styles file

### ISSUE THREAD

**Issue by karlprieb** [janraasch/hugo-bearblog#42]
Currently, the theme provide inline styles that will be downloaded on each page. Why not provide styles as an external asset, so it can be cached by the browser?
With that, when you navigate through pages/posts the browser will not need to download again. It will be ~1.3kb less on each page/post request.

**Comment by kenizl86** [comment]
I second this, mostly because I'm still new to Hugo and I can't figure out where I need to put my CSS file to link to it from a template.

**Comment by metbril** [comment]
> Currently, the theme provide inline styles that will be downloaded on each page. 

That's just how the 'real' Bear Blog is. This theme is a port of that.

> I can't figure out where I need to put my CSS file to link to it

Have a look at the `baseof.html` template:

https://github.com/janraasch/hugo-bearblog/blob/c9b3461ce6b476ca6a344e6f4961e977df175c68/layouts/_default/baseof.html#L20-L23

and this partial file:

https://github.com/janraasch/hugo-bearblog/blob/c9b3461ce6b476ca6a344e6f4961e977df175c68/layouts/partials/custom_head.html#L1-L3

Just create a partial with something like:

```html
<style>
  body {
  font-family: -apple-system,BlinkMacSystemFont,"Avenir Next",Avenir,"Nimbus Sans L",Roboto,Noto,"Segoe UI",Arial,Helvetica,"Helvetica Neue",sans-serif;
}
</style>
```

**Comment by metbril** [comment]
This is also explained in the README:

https://github.com/janraasch/hugo-bearblog#adding-your-branding--colors--css

And if you like you could also include an external stylesheet here with a `<link>` element.

**Comment by karlprieb** [comment]
Thank you @metbril it make sense to keep the same structure of Bear blog as it's a port.
