### ISSUE TITLE
Hardcoded ref to /blog

### ISSUE THREAD

**Issue by metbril** [janraasch/hugo-bearblog#44]
The theme has a hardcoded ref to `/blog` 

https://github.com/janraasch/hugo-bearblog/blob/c9b3461ce6b476ca6a344e6f4961e977df175c68/layouts/_default/list.html#L6

When you use a different section name (like the more or less default 'posts', the link will lead to a 404 page.

Perhaps make this a config parameters or make it dynamic?

**Comment by metbril** [comment]
Would you accept a PR that uses the first item in the mainSections parameter and defaults to "/blog"?

```html
<a href="{{ with .Site.GetPage (index .Site.Params.MainSections 0) }}{{ .RelPermalink }}{{else}}/blog{{ end }}">Remove filter</a>
```

**Comment by metbril** [comment]
I've since discovered there are more hard coded references to /blog that need to be reviewed.

**Comment by joshlawrence** [comment]
@metbril I found this last night while looking at the same issue:

```
./exampleSite/config.toml:  tags = "/blog/:slug"
./layouts/_default/list.html:    <a href="{{ "/blog" | relURL }}">Remove filter</a>
./layouts/partials/nav.html:{{ with .Site.GetPage "/blog" }}
./layouts/partials/nav.html:<a href="{{ "/blog" | relURL }}">Blog</a>
```

not sure if this is helpful or not, but there ya go.

**Comment by metbril** [comment]
Too bad the stale bot closed the issue, since I'm still disappointed this still has not been resolved.
