### ISSUE TITLE
Does this blog supports latex equations?

### ISSUE THREAD

**Issue by underdogliu** [janraasch/hugo-bearblog#47]
Hello and first of all, thanks for the work! Very nice and minimal blog.

I have a simple Q: So after going through the website and samples, I still don't know if it can write latex equations. In markdown usually we are allowed to embed them but not sure if it is the case here.

**Comment by rexarski** [comment]
In short, you probably need to add mathjax support yourself, which can be done in three steps:

1. Create a `mathjax.html` in `layouts/partials` as following:

```html
<script>
    MathJax = {
        tex: {
            inlineMath: [
                ['$', '$'],
                ['\\(', '\\)'],
            ],
        },
        svg: {
            fontCache: 'global',
        },
    };
</script>
<script
    type="text/javascript"
    id="MathJax-script"
    async
    src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml.js"
></script>
```

2. Add `{{ partial "mathjax.html" . }}` in your `header.html` or `custom_head.html` to ensure the above script will be loaded on every page.

Then you can write your $\LaTeX$ the usual way in any `.md` file. But I think what makes `bearblog` stand out is its minimalism and simplicity, and mathjax will, for sure, increases the load time a tiny little bit (maybe).

[Reference](https://www.bodunhu.com/blog/posts/add-mathjax-v3-support-to-jekyll-and-hugo/)
