### ISSUE TITLE
Change code colour schema?

### ISSUE THREAD

**Issue by aparcar** [janraasch/hugo-bearblog#5]
I'm showing some code in my blog but especially strings are hard to read, is it possible to change the colour schema?
![image](https://user-images.githubusercontent.com/16000931/93938089-73835d80-fcc4-11ea-8661-aeeb3c5e01ea.png)

**Comment by janraasch** [comment]
Hi @aparcar, again, anything's possible with Hugo 😜 . Check out https://gohugo.io/getting-started/configuration-markup#highlight for all the configuration options.

E.g. you could add

```toml
[markup]
  [markup.highlight]
    style = "friendly"
```

to your `config.toml`-file to render the same code as shown in the following screenshot

<img width="795" alt="Screenshot 2020-09-24 at 16 43 13" src="https://user-images.githubusercontent.com/425211/94160903-6cf01400-fe85-11ea-9b6e-f90923aa224d.png">

Check out https://xyproto.github.io/splash/docs/all.html for all available `style`s.

Kind regards 👋🏻 ,
Jan

**Comment by aparcar** [comment]
Amazing thank you!

**Comment by janraasch** [comment]
Sure, no problem. 

Also, thank you very much for your monetary recognition 💰 😸 .
