### ISSUE TITLE
All the "Other Elements — abbr, sub, sup, kbd, mark" are stripped from the rendered HTML

### ISSUE THREAD

**Issue by verhovsky** [janraasch/hugo-bearblog#59]
Open https://janraasch.github.io/hugo-bearblog/markdown-syntax-guide/ and scroll down, it looks like this:

<img width="821" alt="Screenshot 2022-11-09 at 20 35 33" src="https://user-images.githubusercontent.com/5687998/200994939-0187935a-19d8-455e-811b-5f5d4497f6a7.png">

In fact, if you look at the HTML in the browser, all the elements have been stripped out and it's just regular `<p>`'s with text in them:

```html
<p>GIF is a bitmap image format.</p><p>H2O</p><p>Xn + Yn = Zn</p><p>Press CTRL+ALT+Delete to end the session.</p><p>Most salamanders are nocturnal, and hunt for insects, worms, and other small creatures.</p>
```

**Comment by verhovsky** [comment]
Useless bot

**Comment by rexarski** [comment]
@verhovsky you can add the following lines in `config.toml` to enable them again.

```toml
[markup.goldmark.renderer]
unsafe = true
```

ps I actually made exactly the same modification to my blog last week, you might [find it useful](https://rexarski.com/blog/add-keyboard-keys-and-highlighting-in-hugo/).

**Comment by verhovsky** [comment]
@janraasch I opened https://janraasch.github.io/hugo-bearblog/markdown-syntax-guide/ and the issue is still there.

**Comment by janraasch** [comment]
Hi @verhovsky,

sorry, I did not explain why I closed this. So here we go:

As @rexarski pointed out the behavior could be changed by setting the `unsafe = true`-flag on the `markup.renderer`.

For the demo site (i.e. `exampleSite/config.toml`) I'd like to keep the **default** `Hugo`-behavior, i.e. `unsafe = false`.

I hope that makes sense.

Cheers!
