### ISSUE TITLE
Mismatched markdown bracket in code preview

### ISSUE THREAD

**Issue by twann4** [janraasch/hugo-bearblog#62]
With markdown code preview, when adding an icon inside a link, the brackets are mismatched:

![Screenshot 2023-02-03 at 13-40-07 Please don't upload my code on GitHub](https://user-images.githubusercontent.com/121837300/216617515-b3370f3b-f048-421c-b833-96c45e11cb2f.png)

Source: https://nogithub.codeberg.page/#how-to-ask-others-to-not-share-my-code-on-github

**Comment by janraasch** [comment]
Hi @twann4, the highlighting is not part of this theme. 

Here's the documentation of the default highlighting on Hugo: https://gohugo.io/content-management/syntax-highlighting/#list-of-chroma-highlighting-languages.

If the problem persists it's best to directly ask on the Hugo community for a solution: https://discourse.gohugo.io/
