### ISSUE TITLE
Home page and Blog page doesn't work with baseURL configuration

### ISSUE THREAD

**Issue by hienvl125** [janraasch/hugo-bearblog#65]
## What
When i hosted hugo with github pages
as [document's recommended](https://gohugo.io/hosting-and-deployment/hosting-on-github/#change-baseurl-in-configtoml) we must config `baseURL` on `config.toml` because github uses `https://<USERNAME>.github.io/<REPOSITORY_NAME>` for a project repository.
```
baseURL = 'https://my-git-username.github.io/blog/'
languageCode = 'en-us'
title = 'My Blog'
theme = 'hugo-bearblog'
```
the hosted example also had this issue
https://janraasch.github.io/hugo-bearblog/

## Reproduce
1. Visit https://janraasch.github.io/hugo-bearblog/
2. Click to "Home" or "Blog" then it causes 404

**Comment by janraasch** [comment]
Hi @hienvl125, thank you for reporting this!

On the demo page the `baseURL` is set via the `command line`-variable `--baseURL`, see https://github.com/janraasch/hugo-bearblog/blob/master/.github/workflows/ci.yml#L26, so your proposed fix won't suffice.

I'll look into it 🙏.
