### ISSUE TITLE
abbr, sub, sup, kbd, mark don't seem to work

### ISSUE THREAD

**Issue by kirillbobyrev** [janraasch/hugo-bearblog#66]
In the demo (https://janraasch.github.io/hugo-bearblog/markdown-syntax-guide/) the last section seems to highlight features that don't seem to work. I don't know if it's intended or not and I can't figure out whether that's a bug or those features are just not supported.

**Comment by rexarski** [comment]
[Issue 59](https://github.com/janraasch/hugo-bearblog/issues/59) might answer your question ;)

**Comment by kirillbobyrev** [comment]
Oh, thank you!

I think it might be worth adding it to the text? Otherwise this is quite confusing.
