### ISSUE TITLE
Features for code blocks

### ISSUE THREAD

**Issue by hiensarahly** [janraasch/hugo-bearblog#7]
Please consider a “Copy” function for code blocks. And perhaps a way to shorten code blocks on screenview for long code snippets. 

I love the BearBlog theme.

**Comment by janraasch** [comment]
Hi @hiensarahly, sorry for the late response 😇. 

I think this is a cool idea and would be more than happy to consider a pull request on this. Added bonus points for keeping the solution low on JavaScript (maybe even no JavaScript?) 🤓.

Cheers 👋,
Jan
