### ISSUE TITLE
Use blog list page as root / home / start page

### ISSUE THREAD

**Issue by janraasch** [janraasch/hugo-bearblog#79]
_Originally posted by @alabhyajindal in https://github.com/janraasch/hugo-bearblog/issues/2#issuecomment-1909758090_

-----

> Hi!
> 
> Thanks for the great theme! 
> 
> I'm having a strange problem. I followed your instructions [here](https://github.com/janraasch/hugo-bearblog/issues/2#issuecomment-691470460) to use the blog list page as home.  The issue is that sometimes I get a blank page on the home section and sometimes I get the blog list. It's completely random.
> 
> I don't have a `content/_index.md` file and my `blog/_index.md` contains: 
>
> ```
> +++
> title = "Blog"
> url = "/"
> [menu]
>   [menu.main]
>     identifier = "blog"
>     weight = 1
> +++
> ```
>
> My website is at https://alabhyajindal.com and the source code is at https://github.com/alabhyajindal/aj, if you want to take a look.

**Comment by janraasch** [comment]
Hi @alabhyajindal, 

I can reproduce this *random* behaviour. No idea why this is happening though 😳... 

You could take the question over to the main `Hugo Discourse` https://discourse.gohugo.io where you'll get a lot more eyes on the issue.

In the mean-time, in your local Hugo repository let's

* remove `content/blog/_index.md` and instead
* create a `content/_index.md`-file with the content

```md
+++
title = "Blog"
[menu]
  [menu.main]
    identifier = "blog"
    weight = 1
+++
```

Plus, create a `layouts/index.html` with the following content

```html
{{ define "main" }}
<content>
  <ul class="blog-posts">
    {{ $blog_posts := where .Site.RegularPages "Type" "in" "blog" }}
    {{ range $blog_posts }}
    <li>
      <span>
        <i>
          <time datetime='{{ .Date.Format "2006-01-02" }}' pubdate>
            {{ .Date.Format (default "02 Jan, 2006" .Site.Params.dateFormat) }}
          </time>
        </i>
      </span>
      <a href="{{ .Permalink }}">{{ .Title }}</a>
    </li>
    {{ else }}
    <li>No posts yet</li>
    {{ end }}
  </ul>
  {{ if .Data.Singular }}
  {{else}}
  <small>
    <div>
      {{ range .Site.Taxonomies.tags }}
      <a href="{{ .Page.Permalink }}">#{{ .Page.Title }}</a>&nbsp; {{ end }}
    </div>
  </small>
  {{ end }}
</content>
{{ end }}
```

That should do the trick.

I hope that helps 🤝.

Kind regards to Meghalaya, India 🇮🇳😁.

Cheers!

**Comment by alabhyajindal** [comment]
Thanks Jan! That works perfectly. Cheers!

**Comment by alabhyajindal** [comment]
I found a solution on the [Hugo Discourse](https://discourse.gohugo.io/t/duplicate-page-generations-when-specifying-url-in-front-matter/47958). It might be helpful to other people wanting to use the blog list as their home page:

1. Create `content/blog/_index.md` with the following contents:

```
+++
title = "Blog"
url = "/"
[menu]
  [menu.main]
    identifier = "blog"
    weight = 1
+++
```

2. Add `home` to `disableKinds` in the `hugo.toml` file:

```
disableKinds = ["taxonomy", "home"]
```
