### ISSUE TITLE
Implement "signup" from bearblog.dev

### ISSUE THREAD

**Issue by amarc** [janraasch/hugo-bearblog#8]
Hello, thanks for great theme.

I want to use it as simple "company presentation" with no nonsense content. I would like for people to "express interes" in service by clicking "Sign up" and leaving their email/name. But instead this form doing anything after, I would just receive email with that data.

So how could I implement https://bearblog.dev/accounts/signup/ with customized fileds (Name, Email, Service interested in) with above logic ?

Thanks, A.

**Comment by janraasch** [comment]
Hi @amarc, sorry for the late response.

> So how could I implement https://bearblog.dev/accounts/signup/ with customized fileds (Name, Email, Service interested in) with above logic?

I think this is a two-fold question.

`1.` **The markup**

You can easily add a `<form>`-tag with whatever fields you need to any page. A quick & dirty solution would be to add

```toml
[markup]
    [markup.goldmark]
        [markup.goldmark.renderer]
            unsafe = true
```

to your `config.toml` and then simply add the necessary `HTML` to your `_index.md` à la

```markdown
# A match made in heaven

I would like for people to express interest in my services by clicking »Sign up«:

<form class="signup" id="signup_form" method="POST">
<p>
    <label for="name">Name:</label>
    <input type="text" name="name" placeholder="Name" required="" id="name">
</p>
<p>
    <label for="email">E-mail:</label>
    <input type="email" name="email" placeholder="E-mail address" required="" id="email">
</p>
<p>
    <label for="service">Service interested in:</label>
    <input type="text" name="service" placeholder="Service" id="service">
</p>
<p>
    <button type="submit">Sign Up</button>
</p>
</form>
```

`2.` **Server-logic** / **Sending you an e-mail on form submissions**

This really depends on how you want to host your website. 

I often use https://www.netlify.com/ for hosting. 

If your site is running on https://www.netlify.com/, you can use »Netlify Forms«. See https://docs.netlify.com/forms/setup/ for the documentation. 

Spoiler 😋: You really only have to add a `data-netlify="true"` to the `<form>`-tag.

I hope that helps 😇.

Let me know, if you have any follow-up questions 👋,
Jan
