### ISSUE TITLE
Scrollbar moves layout a bit

### ISSUE THREAD

**Issue by toyo2333** [janraasch/hugo-bearblog#80]
https://janraasch.github.io/hugo-bearblog/blog/

After clicking "post": Markdown Syntax Guide

The entire page shifts slightly to the left (or towards both sides).

It appears as though the page experienced a brief flash.

**Comment by guites** [comment]
interesting. there seems to be a 15px width difference on the <html> tag between the blog page and internal post pages.

On the internal post pages (which are 15px slimmer), deleting the <content> tag inside the body seems to resolve the problem (it grows the missing 15px).

Also the `<content>` tag is not really defined in the html5 spec is it? I couldn't find any references.

**Comment by toyo2333** [comment]
> interesting. there seems to be a 15px width difference on the `<html>` tag between the blog page and internal post pages.
> 
> On the internal post pages (which are 15px slimmer), deleting the `<content>` tag inside the body seems to resolve the problem (it grows the missing 15px).
> 
> Also the `<content>` tag is not really defined in the html5 spec is it? I couldn't find any references.
> 
> edit: removing the `<content>` tag doesnt actually solves the problem
> 
> ohshit it seems to be the scrollbar. i'm that stupid.

thanks !

so , what should i do now?

**Comment by guites** [comment]
> so , what should i do now?

Well I supposed there isn't anything that can be done, as different browsers will have scrollbars of different widths.

If you check the original bearblog, the same thing is happening:

https://herman.bearblog.dev/ => click on a post or on "Blog"

Since the content remains centered, I think the css is already adequate for these situations.

**Comment by janraasch** [comment]
Hi there 👋,

here is an existing issue on the `Original Bear Blog`-repo: https://github.com/HermanMartinus/bearblog/issues/26

@toyo2333: You could chime in over there ⬆️.

Then, we can pull in a solution into this repo later on.
