### ISSUE TITLE
Render bullet points on blog post list

### ISSUE THREAD

**Issue by toyo2333** [janraasch/hugo-bearblog#82]
want to make the blog post list show the “point” like this
- 2023-12-14 ZXZZZZ
- 2022-12-14 ZXZZZZ

the custom css is

```
    ul.blog-posts li {
        list-style-type: disc;
        display: block;
        margin: 10px 0;
    }
```

it dose NOT work

**Comment by janraasch** [comment]
Hi @toyo2333,

I think you need to 

* apply `list-style-type: disc` to `ul.blog-posts` (not `ul.blog-posts li`). Plus, 
* add `display: list-item` to `ul.blog-posts li`.

I hope that helps 🧤
