### ISSUE TITLE
Add Support for Mermaid.js Diagrams

### ISSUE THREAD

**Issue by cbrgm** [janraasch/hugo-bearblog#83]
## Feature Request: Mermaid.js Support

Integrate Mermaid.js for enhanced diagramming capabilities within blog posts.

**What + Why:**
- Mermaid.js is a JavaScript tool for creating and dynamically modifying diagrams and charts via Markdown-inspired text definitions.
- It would enable users to embed complex diagrams directly into their Hugo Bearblog posts, enhancing the content's visual and instructional quality.
- Adds a powerful tool for technical bloggers and educators who need to include flowcharts, sequence diagrams, class diagrams, etc., in their posts.
- Keeps the blog visually engaging and informative without sacrificing speed or simplicity.

**Comment by janraasch** [comment]
Hi @cbrgm,

thank you for opening this issue 🧤. Nice to meet you 😁.

I have not used [Mermaid](https://mermaid.js.org) myself, but it does look cool. It definitely seems useful for technical bloggers & educators!

I did some quick `duckduckgo`-🦆-ing on `using mermaid.js with hugo`. This post

https://robb.sh/posts/how-to-use-mermaid-diagrams-in-hugo/

has a quick & easy way to get you setup.

If you run into problems or have further questions there's also a discussion on the main Hugo discourse platform https://discourse.gohugo.io/t/correct-way-to-embed-mermaid-js/43491 about how to best embed [Mermaid](https://mermaid.js.org) on Hugo.

I am not sure, if we'd need to add this to theme. It seems like this is more of a general issue. In fact once you have a working shortcut you could ship this as an (independent) [Hugo module](https://gohugo.io/hugo-modules/).

I hope that helps.

Kind regards 👋,
Jan

**Comment by cbrgm** [comment]
Hi @janraasch ,

Thanks for the swift and helpful response!

Mermaid integration looks straightforward with your guidance. I'll explore the links you provided, especially the setup guide and the Hugo forum discussion for any advanced embedding options.

Regarding theme integration, your point about creating a Hugo module makes a lot of sense. It could streamline the process for others facing the same issue.

And what a small world – I'm located in Hamburg! Great to connect with a "neighbor"  in this context. 😁

Best,
@cbrgm
