### ISSUE TITLE
og:title is empty

### ISSUE THREAD

**Issue by toyo2333** [janraasch/hugo-bearblog#84]
home page

<meta property="og:title" content><meta property="og:description" content="Hugo + Bear = :heart:">

the content field is empty

**Comment by janraasch** [comment]
Hi @toyo2333,

nice to meet 🧤😁.

To fill the `og:title` you need to set the `title` as _frontmatter_ on your `_index.md`.

I just added this on the `exampleSite` (see https://github.com/janraasch/hugo-bearblog/commit/ea7bb396cc8c6ca8213f626fc0744a391f76f716#diff-486ed32d79f6e423fee895bca4c1c6d4f33918a0c9f68706a38953c9b78e59e2R1-R7) so you can check it out.

I hope that helps 🤝.

Thank you very much for pointing this out 💜.

Have a great week 👋,
Jan
