### ISSUE TITLE
Remove Line Under Links

### ISSUE THREAD

**Issue by brandonprajogo** [janraasch/hugo-bearblog#90]
Hello. I'm using your theme with my site and it looks great!

But do you know how to remove line under links to make it look nicer? Just like original Bear Blog? Thanks.
<img width="310" alt="hugo bear blog" src="https://github.com/janraasch/hugo-bearblog/assets/166603992/d9ea8fb6-1c34-4da7-ba64-3b1241b8ed1e">
<img width="245" alt="bear blog" src="https://github.com/janraasch/hugo-bearblog/assets/166603992/1fbf6f46-1757-47ae-9540-de6b1907f858">

**Comment by kristianfreeman** [comment]
@brandonprajogo Create a new file called `layouts/partials/custom_head.html`, and add:

```html
<style>
a {
  color: #007bff;
  text-decoration: none;

  &:hover {
    text-decoration: underline;
  }
}
</style>
```

**Comment by brandonprajogo** [comment]
Ok, thanks.

**Comment by brandonprajogo** [comment]
Apparently, making line under links affect accessibility score on PageSpeed. What can I do to solve this?
<img width="947" alt="pagespeed" src="https://github.com/janraasch/hugo-bearblog/assets/166603992/9ae16277-0f6f-4939-826c-370fd2a15eed">

**Comment by mansoorbarri** [comment]
it says right there, the links just rely on colour. maybe add the line when the user hovers or smth
