### ISSUE TITLE
Date Style, Commenting, and Toast Button

### ISSUE THREAD

**Issue by brandonprajogo** [janraasch/hugo-bearblog#91]
Hi @janraasch, thank you for creating this beautiful theme! I really enjoy the minimal look of this theme and use it for my main blog.

I'm curious if can I change the looks of post date, for instance changing the style from italic to normal and also change the font, just like Herman's Blog in Bear?
![Screenshot_20240427_084750_Chrome](https://github.com/janraasch/hugo-bearblog/assets/166603992/a312ec29-3d40-4045-8bbd-35c2c05c9a27)

I think it also great to add "Toast this post" button that originally ship in bear blog. I know you have open the issue a long time ago, I have another question but the issue has been closed for long time and doesn't solve my problem, you can [read it here.](https://github.com/janraasch/hugo-bearblog/issues/1#issuecomment-2081020886)

I'm also curious does this theme supports commenting? If it does, what commenting system would you recommend? Disqus or something else?

That's all of my question, I really hope you can reply my questions. Have a nice day!

**Comment by janraasch** [comment]
Hi @brandonprajogo, please excuse the late reply:

### looks

I haven't had time to keep up with the `HTML` & `CSS` changes on the original bearblog: https://github.com/HermanMartinus/bearblog/blob/master/templates/styles/blog/default.css

I think once we are up to date, we should have what your are looking for.

In the meantime you may always overwrite any `layout`-file in your own `hugo` repo.

### toast

See https://github.com/janraasch/hugo-bearblog/issues/1#issuecomment-2583208142

### comments

I don't use comments. I personally rather have people e-mail me. So I am afraid I cannot recommend anything.

Again, I am really sorry it took me so long to reply.

Have a great start of the year. Kind regards,
Jan

**Comment by janraasch** [comment]
Hi @brandonprajogo, looks like @rokcso has you covered with a `toast`-button: https://github.com/janraasch/hugo-bearblog/issues/100.
