### ISSUE TITLE
Pagination not worked

### ISSUE THREAD

**Issue by productsolo** [janraasch/hugo-bearblog#94]
How to activate paginator in hugo-bearblog theme?

I was added on config.toml:

```
[pagination]
  disableAliases = false
  pagerSize = 5
  path = 'page'
```

but, not worked for me. Thank You.

**Comment by janraasch** [comment]
Hi @productsolo, `Hugo Bear Blog` currently does not come with pagination, see https://github.com/janraasch/hugo-bearblog/issues/64#issuecomment-1467929833.
