### ISSUE TITLE
how to enable TOC

### ISSUE THREAD

**Issue by toyo2333** [janraasch/hugo-bearblog#97]
how to enable TOC？

**Comment by janraasch** [comment]
Hi @toyo2333, nice to meet you 🤝😁.

ℹ️ Currently `Hugo Bear Blog` does **not** come with `Table of Contents` (see https://gohugo.io/methods/page/tableofcontents/) on any of the included templates/layouts (see https://github.com/janraasch/hugo-bearblog/tree/master/layouts), so you'd have to **supply your own**.

▶️ If you need help head over to the `Hugo Discourse` https://discourse.gohugo.io. There are a lot of knowledgable *& friendly* people on there. They'll help you out in no time 🚀 ☺️.

Have a good weekend 👋🏻 👋🏻 👋🏻
