### ISSUE TITLE
Scroll instead of wrap

### ISSUE THREAD

**Issue by avidseeker** [janraasch/hugo-bearblog#98]
https://avidseeker.github.io/arabic-latex/

Compare with how github adds a scroll bar:
```
Lopadotemachoselachogaleokranioleipsanodrimhypotrimmatosilphiokarabomelitokatakechymenokichlepikossyphophattoperisteralektryonoptekephalliokigklopeleiolagoiosiraiobaphetraganopterygon is a fictional dish originating from Aristophanes' 391 B.C.
```

![image](https://github.com/user-attachments/assets/3e1f3547-dfd9-423b-9202-3055774303fa)

**Comment by janraasch** [comment]
Hi @avidseeker, I don't see a scrollbar here ⬇️🤓.

<img width="927" alt="Screenshot 2024-08-09 at 12 02 18" src="https://github.com/user-attachments/assets/92113c3b-781d-4d1d-8e2e-4aadd8ed0d13">

💭 **thoughts** I might be misunderstanding your request, but you could try to set the `height` via CSS on the `pre code` element to limit the height to one line of code if that is what you want.

ℹ️ The highlighting of code is not part of this theme itself, it's a general `Hugo` feature, see https://gohugo.io/getting-started/configuration-markup/#highlight. If you need help, you will probably find what you need on the `Hugo Discouse`, see https://discourse.gohugo.io.

**Comment by avidseeker** [comment]
![image](https://github.com/user-attachments/assets/01dec56c-1ce8-48d5-99d7-0d732e041f0c)

Interesting, what browser or OS do you use?

**Comment by janraasch** [comment]
I see. Yea, Mac OS usually does not render scrollbars.
